angular.module('appMaps', [])
  .controller('MapController', ['$scope', function($scope) {

  }])

  //angular directive tied to the my-map element in index.html.  This replaces my-map with the DOM elments generated by the template and modifoed by the link function
  .directive('myMap', function() {
    console.log('test');

    var link = function(scope, element, attrs) {
      var map;

      // map config, default values for now
      var mapOptions = {
        center: new google.maps.LatLng(50, 2),
        zoom: 4,
        scrollwheel: false,
        show:true
      };

      // new instance of a google map, added to the first element in element
      var initMap = function() {
        map = new google.maps.Map(element[0], mapOptions);
       };

      initMap();
    };

    return {
      template: '<div id="gmap"></div>',
      replace: true,
      link: link
    };
  });
